import { Currency } from "./reducers/currenciesReducer";

const c = (name: string, symbol: string, coingeckoId: string): Currency => ({
  name, symbol, type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId, supported: true,
});

const fiat = (name: string, symbol: string): Currency => ({
  name, symbol, type: "fiat", amount: 0, usdEquivalent: 0, coingeckoId: "", supported: true,
});

// Local currency data — all Nexo supported assets
// Source: https://support.nexo.com/article/supported-crypto-assets
export const currencyData: Currency[] = [
  // === Fully Supported ===
  c("Bitcoin", "BTC", "bitcoin"),
  c("Ethereum", "ETH", "ethereum"),
  c("NEXO Token", "NEXO", "nexo"),
  c("XRP", "XRP", "ripple"),
  c("Tether", "USDT", "tether"),
  c("USD Coin", "USDC", "usd-coin"),
  c("Pax Dollar", "USDP", "paxos-standard"),
  c("Dai", "DAI", "dai"),
  c("Bitcoin Cash", "BCH", "bitcoin-cash"),
  c("Litecoin", "LTC", "litecoin"),
  c("BNB", "BNB", "binancecoin"),
  c("Stellar", "XLM", "stellar"),
  c("PAX Gold", "PAXG", "pax-gold"),
  c("Chainlink", "LINK", "chainlink"),
  c("TRON", "TRX", "tron"),
  c("Cardano", "ADA", "cardano"),
  c("Polkadot", "DOT", "polkadot"),
  c("Solana", "SOL", "solana"),
  c("Dogecoin", "DOGE", "dogecoin"),
  c("Uniswap", "UNI", "uniswap"),
  c("Axie Infinity", "AXS", "axie-infinity"),
  c("Polygon", "POL", "matic-network"),
  c("GALA", "GALA", "gala"),
  c("SushiSwap", "SUSHI", "sushi"),
  c("Curve DAO Token", "CRV", "curve-dao-token"),
  c("Aave", "AAVE", "aave"),
  c("NEAR Protocol", "NEAR", "near"),
  c("ApeCoin", "APE", "apecoin"),
  c("1inch", "1INCH", "1inch"),
  c("Maker", "MKR", "maker"),
  c("Decentraland", "MANA", "decentraland"),
  c("The Sandbox", "SAND", "the-sandbox"),
  c("Avalanche", "AVAX", "avalanche-2"),
  c("Lido DAO", "LDO", "lido-dao"),
  c("Ethereum Name Service", "ENS", "ethereum-name-service"),
  c("The Graph", "GRT", "the-graph"),
  c("Compound", "COMP", "compound-governance-token"),
  c("StepN", "GMT", "stepn"),
  c("Synthetix", "SNX", "havven"),
  c("Chiliz", "CHZ", "chiliz"),
  c("Convex Finance", "CVX", "convex-finance"),
  c("Kyber Network", "KNC", "kyber-network-crystal"),
  c("Basic Attention Token", "BAT", "basic-attention-token"),
  c("yearn.finance", "YFI", "yearn-finance"),
  c("PancakeSwap", "CAKE", "pancakeswap-token"),
  c("Arbitrum", "ARB", "arbitrum"),
  c("Hedera", "HBAR", "hedera-hashgraph"),
  c("Algorand", "ALGO", "algorand"),
  c("Optimism", "OP", "optimism"),
  c("Cosmos", "ATOM", "cosmos"),
  c("Worldcoin", "WLD", "worldcoin-wld"),
  c("Injective", "INJ", "injective-protocol"),
  c("Celestia", "TIA", "celestia"),
  c("SHIBA INU", "SHIB", "shiba-inu"),
  c("ONDO", "ONDO", "ondo-finance"),
  c("PENDLE", "PENDLE", "pendle"),
  c("AltLayer", "ALT", "altlayer"),
  c("Ethena", "ENA", "ethena"),
  c("PEPE", "PEPE", "pepe"),
  c("ether.fi", "ETHFI", "ether-fi"),
  c("RENDER", "RENDER", "render-token"),
  c("FLOKI", "FLOKI", "floki"),
  c("EigenLayer", "EIGEN", "eigenlayer"),
  c("Artificial Superintelligence Alliance", "FET", "artificial-superintelligence-alliance"),
  c("ImmutableX", "IMX", "immutable-x"),
  c("Morpho", "MORPHO", "morpho"),
  c("Mantle", "MNT", "mantle"),
  c("Wrapped Bitcoin", "WBTC", "wrapped-bitcoin"),
  c("dogwifhat", "WIF", "dogwifcoin"),
  c("Pump.fun", "PUMP", "pump-fun"),
  c("Toncoin", "TON", "the-open-network"),
  c("Sky", "SKY", "sky"),
  c("Euro Coin", "EURC", "euro-coin"),
  c("Plasma", "XPL", "plasma-2"),
  c("Tether Gold", "XAUT", "tether-gold"),

  // === Limited Assets ===
  c("THORChain", "RUNE", "thorchain"),
  c("Kusama", "KSM", "kusama"),
  c("GMX", "GMX", "gmx"),
  c("Aptos", "APT", "aptos"),
  c("Osmosis", "OSMO", "osmosis"),
  c("BONK", "BONK", "bonk"),
  c("Flare", "FLR", "flare-networks"),
  c("Sei", "SEI", "sei-network"),
  c("Sui", "SUI", "sui"),
  c("Wormhole", "W", "wormhole"),
  c("Internet Computer", "ICP", "internet-computer"),
  c("Filecoin", "FIL", "filecoin"),
  c("Jupiter", "JUP", "jupiter-exchange-solana"),
  c("Book of Meme", "BOME", "book-of-meme"),
  c("Stacks", "STX", "blockstack"),
  c("Kaspa", "KAS", "kaspa"),
  c("Bittensor", "TAO", "bittensor"),
  c("Sonic", "S", "sonic-3"),
  c("OFFICIAL TRUMP", "TRUMP", "official-trump"),
  c("Berachain", "BERA", "berachain"),
  c("Pudgy Penguins", "PENGU", "pudgy-penguins"),
  c("Vaulta", "A", "vaulta"),
  c("Enjin", "ENJ", "enjincoin"),
  c("dYdX", "DYDX", "dydx-chain"),
  c("World Liberty Financial", "WLFI", "world-liberty-financial"),
  c("Aster", "ASTER", "aster-defi"),
  c("Monad", "MON", "monad"),
  c("Frax", "FRAX", "frax"),

  // === Legacy (no longer on Nexo but may appear in old CSVs) ===
  c("TerraClassicUSD", "USTC", "terrausd"),
  c("Terra Luna 2", "LUNA2", "terra-luna-2"),
  c("Terra Classic", "LUNC", "terra-luna"),
  c("EOS", "EOS", "eos"),
  c("EthereumPoW", "ETHW", "ethereum-pow-iou"),
  c("Frax Share", "FXS", "frax-share"),
  c("Sweat Economy", "SWEAT", "sweatcoin"),
  c("TrueUSD", "TUSD", "true-usd"),

  // === Fiat ===
  fiat("US Dollar", "USD"),
  fiat("Euro", "EUR"),
  fiat("British Pound", "GBP"),
];
