import { Currency } from "./reducers/currenciesReducer";

// Local currency data — replaces Firebase Firestore
export const currencyData: Currency[] = [
  { name: "Bitcoin", symbol: "BTC", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "bitcoin", supported: true },
  { name: "Ethereum", symbol: "ETH", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "ethereum", supported: true },
  { name: "Ripple", symbol: "XRP", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "ripple", supported: true },
  { name: "Chainlink", symbol: "LINK", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "chainlink", supported: true },
  { name: "Dogecoin", symbol: "DOGE", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "dogecoin", supported: true },
  { name: "Nexo", symbol: "NEXO", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "nexo", supported: true },
  { name: "USD Coin", symbol: "USDC", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "usd-coin", supported: true },
  { name: "Terra Luna 2", symbol: "LUNA2", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "terra-luna-2", supported: true },
  { name: "TerraClassicUSD", symbol: "USTC", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "terrausd", supported: true },
  { name: "Polkadot", symbol: "DOT", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "polkadot", supported: true },
  { name: "Cardano", symbol: "ADA", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "cardano", supported: true },
  { name: "Polygon", symbol: "MATIC", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "matic-network", supported: true },
  { name: "Stellar", symbol: "XLM", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "stellar", supported: true },
  { name: "Bitcoin Cash", symbol: "BCH", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "bitcoin-cash", supported: true },
  { name: "Litecoin", symbol: "LTC", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "litecoin", supported: true },
  { name: "EOS", symbol: "EOS", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "eos", supported: true },
  { name: "TRON", symbol: "TRX", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "tron", supported: true },
  { name: "Binance Coin", symbol: "BNB", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "binancecoin", supported: true },
  { name: "Kusama", symbol: "KSM", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "kusama", supported: true },
  { name: "NEAR Protocol", symbol: "NEAR", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "near", supported: true },
  { name: "Solana", symbol: "SOL", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "solana", supported: true },
  { name: "Avalanche", symbol: "AVAX", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "avalanche-2", supported: true },
  { name: "Dai", symbol: "DAI", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "dai", supported: true },
  { name: "EthereumPoW", symbol: "ETHW", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "ethereum-pow-iou", supported: true },
  { name: "Terra Classic", symbol: "LUNC", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "terra-luna", supported: true },
  { name: "Polygon", symbol: "POL", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "matic-network", supported: true },
  { name: "Tether", symbol: "USDT", type: "crypto", amount: 0, usdEquivalent: 0, coingeckoId: "tether", supported: true },
  { name: "US Dollar", symbol: "USD", type: "fiat", amount: 0, usdEquivalent: 0, coingeckoId: "", supported: true },
  { name: "Euro", symbol: "EUR", type: "fiat", amount: 0, usdEquivalent: 0, coingeckoId: "", supported: true },
  { name: "British Pound", symbol: "GBP", type: "fiat", amount: 0, usdEquivalent: 0, coingeckoId: "", supported: true },
];
